### ISSUE TITLE
Imagery with labels thumbnail missing with 3.12compact

### ISSUE THREAD

**Issue by mgayheart** [Esri/arcgis-dijit-basemap-toggle-js#3]
I have been using the basemap toggle with a website and the 3.12compact version of the js api. I was toggling between Streets and Imagery with Labels. Everything has worked fine for a few months, but recently the thumbnail for Imagery with Labels went missing.
![image](https://cloud.githubusercontent.com/assets/4136905/6598848/bc807ca2-c7dc-11e4-82c9-d3a4583c2ead.png)

The errors in the browser are below and mention not being able to find http://www.arcgis.com/sharing/rest/content/items/413fd05bbd7342f5991d5ec96f4f8b18/info/thumbnail/tempimagery_with_labels_ne_usa.png.

![image](https://cloud.githubusercontent.com/assets/4136905/6598831/a531a346-c7dc-11e4-881b-0dd51f4d0be8.png)

If I test the site with 3.13compact it works, but I'm not sure I can update production to 3.13 yet.

I know that the Streets thumbnail still does work, but haven't tried any of the other basemaps.

Thanks!

**Comment by mgayheart** [comment]
The issue can actually be seen if you just click the "View Demo" link on the front page of this repository.

**Comment by driskull** [comment]
hey @mgayheart sorry about that. Here's a workaround if you haven't figured it out already.

http://jsbin.com/segiho/1/

**Comment by mgayheart** [comment]
We moved production to 3.13, but the workaround is good to know. Not a big deal but the missing thumbnail is still a problem on the Demo page for this repo so it would be good to employ the workaround on the page or move up to 3.13. Thanks!

**Comment by driskull** [comment]
Thanks! got it updated :+1:
